title: cloudIA - Cloud Infrastrcuture Automation
description: educational grade development tools
google_analytics:
show_downloads: true

# Make directory-style links
permalink: pretty

defaults:
plugins:
- jekyll-optional-front-matter
